package com.mulesoft.wcfconsumer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Sat Jun 30 22:59:12 BRT 2012
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "IWCFRetailService")
@XmlSeeAlso({ObjectFactory.class})
public interface IWCFRetailService {

    @WebResult(name = "CreateOrderResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IWCFRetailService/CreateOrder", output = "http://tempuri.org/IWCFRetailService/CreateOrderResponse")
    @RequestWrapper(localName = "CreateOrder", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.wcfconsumer.CreateOrder")
    @ResponseWrapper(localName = "CreateOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.wcfconsumer.CreateOrderResponse")
    @WebMethod(operationName = "CreateOrder", action = "http://tempuri.org/IWCFRetailService/CreateOrder")
    public java.lang.String createOrder(
        @WebParam(name = "order", targetNamespace = "http://tempuri.org/")
        com.mulesoft.wcfconsumer.Order order
    );
}
