
package com.mulesoft.wcfconsumer;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Sat Jun 30 22:59:12 BRT 2012
 * Generated source version: 2.1.3
 * 
 */

public final class IWCFRetailService_BasicHttpBindingIWCFRetailService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WCFRetailService");

    private IWCFRetailService_BasicHttpBindingIWCFRetailService_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WCFRetailService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WCFRetailService ss = new WCFRetailService(wsdlURL, SERVICE_NAME);
        IWCFRetailService port = ss.getBasicHttpBindingIWCFRetailService();  
        
        {
        System.out.println("Invoking createOrder...");
        com.mulesoft.wcfconsumer.Order _createOrder_order = null;
        java.lang.String _createOrder__return = port.createOrder(_createOrder_order);
        System.out.println("createOrder.result=" + _createOrder__return);


        }

        System.exit(0);
    }

}
