
package com.mulesoft.demo.wcfservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu May 24 17:54:15 VET 2012
 * Generated source version: 2.1.3
 * 
 */

public final class IService1_WSHttpBindingIService1_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Service1");

    private IService1_WSHttpBindingIService1_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Service1.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service1 ss = new Service1(wsdlURL, SERVICE_NAME);
        IService1 port = ss.getWSHttpBindingIService1();  
        
        {
        System.out.println("Invoking createOrder...");
        com.mulesoft.demo.wcfservice.Order _createOrder_order = null;
        java.lang.String _createOrder__return = port.createOrder(_createOrder_order);
        System.out.println("createOrder.result=" + _createOrder__return);


        }

        System.exit(0);
    }

}
