package com.mulesoft.demo.wcfservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu May 24 17:54:15 VET 2012
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "IService1")
@XmlSeeAlso({ObjectFactory.class})
public interface IService1 {

    @WebResult(name = "CreateOrderResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IService1/CreateOrder", output = "http://tempuri.org/IService1/CreateOrderResponse")
    @RequestWrapper(localName = "CreateOrder", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.demo.wcfservice.CreateOrder")
    @ResponseWrapper(localName = "CreateOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.mulesoft.demo.wcfservice.CreateOrderResponse")
    @WebMethod(operationName = "CreateOrder", action = "http://tempuri.org/IService1/CreateOrder")
    public java.lang.String createOrder(
        @WebParam(name = "order", targetNamespace = "http://tempuri.org/")
        com.mulesoft.demo.wcfservice.Order order
    );
}
