
/*
 * 
 */

package com.mulesoft.demo.wcfservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu May 24 17:54:15 VET 2012
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "Service1", 
                  wsdlLocation = "http://localhost:2628/Service1.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class Service1 extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/", "Service1");
    public final static QName WSHttpBindingIService1 = new QName("http://tempuri.org/", "WSHttpBinding_IService1");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:2628/Service1.svc?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:2628/Service1.svc?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Service1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service1() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IService1
     */
    @WebEndpoint(name = "WSHttpBinding_IService1")
    public IService1 getWSHttpBindingIService1() {
        return super.getPort(WSHttpBindingIService1, IService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IService1
     */
    @WebEndpoint(name = "WSHttpBinding_IService1")
    public IService1 getWSHttpBindingIService1(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIService1, IService1.class, features);
    }

}
